<?php
$typeArr[1] = 'SEO教程';
$typeArr[2] = 'SEO技术';
$typeArr[3] = 'SEO算法';
$typeArr[4] = 'SEO案例';
$typeArr[5] = 'SEO培训';
$typeArr[6] = '网站建设';
$typeArr[7] = '关于我们';
$typeArr[8] = '收录问题';
$typeArr[9] = '站内优化';
$typeArr[10] = '站外优化';
$typeArr[11] = '优化基础';
$typeArr[12] = '常规技术';
$typeArr[13] = '黑帽技术';
$typeArr[14] = '百度算法';
$typeArr[15] = '搜狗算法';
$typeArr[16] = '谷歌算法';
$typeArr[17] = '经典案例';
$typeArr[18] = '快排案例';
$typeArr[19] = '免费视频';
$typeArr[20] = '付费教程';
$typeArr[21] = '织梦模板';
$typeArr[22] = '帝国模板';
$typeArr[23] = '其他源码';
$typeArr[24] = '关于本站';
$typeArr[25] = '联系我们';
?>