<article class="item fl">
            <div class="clearfix">
              <div class="title-wrap clearfix"> <a class="category transition ellipsis br fl" href="[field:arcurl/]" title="[field:title /]"> [field:typename/] </a>
                <h2 class="title ellipsis fl"> <a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a> </h2>
              </div>
              <a class="thumbnail fl" href="[field:arcurl/]" title="[field:title /]"> <img class="img-cover br" src="[field:litpic/]" alt="[field:title /]" title="[field:title /]"> </a>
              <div class="fr-wrap">
                <p class="intro br clearfix">[field:description function="cn_substr(@me,120)"/]... </p>
              </div>
            </div>
          </article>