<article class="article-list br mb sb clearfix">
          <figure class="figure fl"> <a class="thumbnail" href="[field:arcurl/]" title="[field:title /]"> <img class="img-cover br" src="[field:litpic/]" alt="[field:title /]"> </a> </figure>
          <div class="content">
            <h2 class="title ellipsis m-multi-ellipsis"><a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a></h2>
            <p class="intro hidden-sm"> [field:description function="cn_substr(@me,220)"/]... </p>
            <p class="data clearfix"> <span class="hidden-sm-md-lg author fl"><i class="iconfont icon-user"></i></span>
              <time class="time fl" datetime="[field:pubdate function="GetDateMK(@me)"/]" title="[field:pubdate function="GetDateMK(@me)"/]">
              <i class="iconfont icon-time"></i>[field:pubdate function="GetDateMK(@me)"/]
              </time>
              <span class="view fl"><i class="iconfont icon-view"></i>[field:click/]</span> <span class="hidden-sm-md-lg tag ellipsis fr"> <i class="iconfont icon-tag"></i> #<a href='/tags.php?/%E6%8A%96%E9%9F%B3%E8%B5%9A/'>抖音赚</a>  </span> </p>
          </div>
        </article>