<?php
$z[0]=Array("arcurl","",35,50);
$z[0][4]=array();
$z[1]=Array("title","",59,74);
$z[1][4]=array();
$z[2]=Array("litpic","",109,124);
$z[2][4]=array();
$z[3]=Array("title","",131,146);
$z[3][4]=array();
$z[4]=Array("title","",260,275);
$z[4][4]=array();
$z[5]=Array("pubdate","",368,410);
$z[5][4]=array();
$z[5][4]['function']="GetDateMK(@me)";
$z[6]=Array("click","",473,487);
$z[6][4]=array();

?>