<li class="list clearfix"><a href="[field:arcurl/]" title="[field:title /]"><span class="img-wrap"><img src="[field:litpic/]" alt="[field:title /]" class="img-cover br random-img"></span>
              <div class="new-text">
                <p class="title">[field:title /]</p>
                <div class="info"><span class="time"><i class="iconfont icon-time"></i>[field:pubdate function="GetDateMK(@me)"/]</span><span class="comment"><i class="iconfont icon-view"></i>[field:click/]</span></div>
              </div>
              </a></li>