<article class="item fl"> <a class="thumbnail" href="[field:arcurl/]" title="[field:title /]"> <img class="img-cover br" src="[field:litpic/]" alt="[field:title /]" title="[field:title /]"> </a> <a class="category brightness transition br" href="[field:arcurl/]" title="[field:title /]">[field:typename/]</a>
            <h2 class="title multi-ellipsis"><a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a></h2>
            <div class="num clearfix"> <span class="view ellipsis fl"><i class="iconfont icon-view"></i>[field:click/]</span> </span>
              <time class=" time ellipsis fr" datetime="[field:pubdate function="GetDateMK(@me)"/]" title="[field:pubdate function="GetDateMK(@me)"/]">[field:pubdate function="GetDateMK(@me)"/]</time>
            </div>
          </article>