<?php
$z[0]=Array("global","",424,447);
$z[0][4]=array();
$z[0][4]['name']="cfg_name";
$z[1]=Array("field","",488,510);
$z[1][4]=array();
$z[1][4]['name']="keywords";
$z[2]=Array("field","",550,601);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",2723,2758);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("tag"," <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a> ",3274,3390);
$z[4][4]=array();
$z[4][4]['row']="60";
$z[4][4]['sort']="new";
$z[5]=Array("tag"," <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a> ",3555,3673);
$z[5][4]=array();
$z[5][4]['row']="60";
$z[5][4]['sort']="month";
$z[6]=Array("tag"," <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a> ",3832,3950);
$z[6][4]=array();
$z[6][4]['row']="100";
$z[6][4]['sort']="rand";
$z[7]=Array("include","",4033,4069);
$z[7][4]=array();
$z[7][4]['filename']="right.htm";
$z[8]=Array("include","",4078,4113);
$z[8][4]=array();
$z[8][4]['filename']="foot.htm";

?>